a = int(input("Введите первое число"))
b = int(input("Введите второе число"))
c = int(input("Введите третье число"))
d = int(input("Введите четвертое число"))
x = (a + b) / (c + d)
x = float('{:.2f}'.format(x))
print(x)